Rework apps, update admin, remove lodash
firebase/firebase-functions pull request #1144
Opened 2022-06-17 00:21 UTC by inlined

This change involved a number  of small things that kinda got smushed together. Sorry.

1. I changed the "apps" library. It originally was supposed to hold a refcounted copy of apps logged in with user auth overrides. Ripping all that code out felt good! (including ripping out `before` and `after` in `makeCloudFunction`. Importantly, we will now share the default app if it already exists when we need it. This should help consolidate network connections/caches. OTOH, it could lead to subtle bugs. Push back if you think this optimization is too dangerous.
2. Since we updated the admin SDK version in `launch.next` already, I switched over to the v10 syntax so that we load fewer files on demand.
3. I cleaned up lodash in a few files and decided to pull on the thread until lodash is removed from the SDK entirely.
4. In order to efficiently implement a lodash method, I had to raise the typescript target to ES2019, which is covered by our new supported engines (14 & 16)

2022-06-21 15:09 UTC, colerogers requested changes
Couple leftover comments

2022-06-21 15:09 UTC, colerogers commented on src/common/app.ts
> +  // }
remove these comments

2022-06-21 18:58 UTC, taeold approved these changes

2022-06-21 18:58 UTC, taeold commented on src/index.ts
> +export const app = { setEmulatedAdminApp };
sigh I wish I knew why this function is needed for the emulator to work.

(I have a theory that this is just a historical artifact before admin sdk natively supported the emulator)

2022-06-21 18:58 UTC, taeold commented on src/common/app.ts
> + * A) We complete the new emulator and no longer depend on monkeypatching
actively researching this. I _think_ recent versions of the admin sdk doesn't rely on this monkey patching, and I'll try to confirm/deny this.

2022-06-26 19:33 UTC, inlined commented
@colerogers You left this with a change request. Does uncommenting those lines fix everything?

2022-06-27 15:24 UTC, colerogers approved these changes

2022-06-27 19:17 UTC, merged