fix: prioritize boolean cors value over debug flags
firebase/firebase-functions pull request #1189
Opened 2022-08-12 06:30 UTC by stfsy

### Description

As discussed in https://github.com/firebase/firebase-tools/issues/4862 it's not possible to disable cors in v2 functions, because the emulator enables the debug feature for cors overriding `opts.cors`.

If we could prioritize the boolean flag over the debug feature, we could have both: The ability to disable cors and also prioritize the debug flag over user provided configuration.

### Code sample

2022-08-25 17:16 UTC, taeold requested changes

2022-08-25 17:16 UTC, taeold commented on src/v2/providers/https.ts
> +  if (opts.cors !== false && (isDebugFeatureEnabled('enableCors') || 'cors' in opts)) {
oof lots conditions here that's making my head spin 🤯 

What if we do this in longer form:

```suggestion
  if (isDebugFeatureEnabled('enableCors') || 'cors' in opts) {
    let origin = opts.cors;
    if (isDebugFeatureEnabled('enableCors')) {
      // Respect `cors: false` to turn off cors even if debug feature is enabled.
      origin = opts.cors === false ? false : true 
    }
  }
```

2022-08-25 19:54 UTC, stfsy commented
@taeold updated as per suggestion and rebased

2022-08-25 21:23 UTC, taeold approved these changes
LGTM - please fix formatting!

Thank you for an awesome contribution!

2022-09-11 19:31 UTC, stfsy commented
@taeold anything else I can do?

2022-09-11 19:37 UTC, stfsy commented
@taeold got it now, had to run `npm run format:fix` to fix the formatting error. I committed and pushed the changes just a few seconds ago.

2022-12-15 16:27 UTC, colerogers commented
@stfsy I fixed your merge conflicts but it looks like you need to run `npm run format` one more time before we can merge this.

2022-12-15 17:34 UTC, stfsy commented
@colerogers thank you very much 🙂 I ran `npm run format` and commited+pushed the results

2022-12-15 18:03 UTC, merged